baseURL = "https://dunkloestus.github.io/Wired-Blog"
languageCode = "en-us"
title = "Present Day, Present Time"
# REMOVED: theme = "terminal" ← This line causes the error when using Hugo Modules

# Enable pagination
[pagination]
pagerSize = 5

# Required for Chroma syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[params]
  # Content directory
  contentTypeName = "posts"
  
  # Menu items to show
  showMenuItems = 3
  
  # Theme appearance
  fullWidthTheme = false
  centerTheme = true
  
  # Auto cover images
  autoCover = true
  
  # Show last updated
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  
  # Reading time
  readingTime = true
  
  # Table of contents
  Toc = true
  TocTitle = "Navigation"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Present Day, Present Time"
    
    [languages.en.params]
      subtitle = "And you don't seem to understand..."
      owner = "Your Name"
      keywords = "blog, cyberpunk, technology, thoughts"
      copyright = "© Present Day"
      menuMore = "Show more"
      readMore = "Continue reading"
      readOtherPosts = "Other transmissions"
      newerPosts = "Newer"
      olderPosts = "Older"
      missingContentMessage = "Connection lost..."
      missingBackButtonLabel = "Return to protocol"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Wired-Blog"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "posts"
          name = "Logs"
          url = "/posts"
        [[languages.en.menu.main]]
          identifier = "archive"
          name = "Archive"
          url = "/archive"

# Hugo Module configuration (this replaces the theme declaration)
[module]
  [[module.imports]]
    path = 'github.com/panr/hugo-theme-terminal/v4'
