baseURL = "https://dunkloestus.github.io/Wired-Blog/"
languageCode = "en-us"
title = "Wired Blog"
canonifyURLs = true
relativeURLs = false
staticDir = ["static"]

[pagination]
pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "monokai"

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  readingTime = true
  Toc = true
  TocTitle = "Navigation"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Wired Blog"
    
    [languages.en.params]
      subtitle = "And you don't seem to understand..."
      owner = "Dunkloestus"
      keywords = "blog, cyberpunk, technology, thoughts, lain"
      copyright = "© Present Day, Present Time, made by Dunkloestus"
      menuMore = "Show more"
      readMore = "Continue reading"
      readOtherPosts = "Other transmissions"
      newerPosts = "Newer"
      olderPosts = "Older"
      missingContentMessage = "Connection lost..."
      missingBackButtonLabel = "Return to protocol"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Wired-Blog"
        logoHomeLink = "/"  # ← FIXED: Proper relative path

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "posts"
          name = "Logs"
          url = "/posts"

[module]
  [[module.imports]]
    path = 'github.com/panr/hugo-theme-terminal/v4'
