baseURL = "https://dunkloestus.github.io/Wired-Blog/"
languageCode = "en-us"
title = "Present Day, Present Time"

# Enable pagination
[pagination]
pagerSize = 5

# Required for Chroma syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[params]
  # Content directory
  contentTypeName = "posts"
  
  # Menu items to show
  showMenuItems = 3
  
  # Theme appearance
  fullWidthTheme = false
  centerTheme = true
  
  # Auto cover images
  autoCover = true
  
  # Show last updated
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  
  # Reading time
  readingTime = true
  
  # Table of contents
  Toc = true
  TocTitle = "Navigation"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Present Day, Present Time"
    
    [languages.en.params]
      subtitle = "And you don't seem to understand..."
      owner = "Dunkloestus"
      keywords = "blog, cyberpunk, technology, thoughts, lain"
      copyright = "© Present Day, Present Time"
      menuMore = "Show more"
      readMore = "Continue reading"
      readOtherPosts = "Other transmissions"
      newerPosts = "Newer"
      olderPosts = "Older"
      missingContentMessage = "Connection lost..."
      missingBackButtonLabel = "Return to protocol"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Wired-Blog"
        logoHomeLink = "/Wired-Blog/"  # ← Fixed: Added /Wired-Blog/ subdirectory

      [languages.en.menu]
      ##  [[languages.en.menu.main]]
        #  identifier = "about"
         # name = "Identity"
          #url = "/about"
       # [[languages.en.menu.main]]
       #   identifier = "posts"
        #  name = "Logs"
        #  url = "/posts"
        [[languages.en.menu.main]]
          identifier = "archive"
          name = "Archive"
          url = "/content/posts/"

# Hugo Module configuration
[module]
  [[module.imports]]
    path = 'github.com/panr/hugo-theme-terminal/v4'
